language: cpp
dist: xenial
compiler: gcc

install: 
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # OCLint
  - ./install_oclint

script: 
  # Build and run tests
  - qmake
  - make --silent debug
  # - ./wiering_vector
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # OCLint
  - ./do_oclint
